### ISSUE TITLE
Import nzbs via web ui spawns request for arguments. How do I pass args to a tmux frame?

### ISSUE THREAD

**Issue by DrakeJones** [nZEDb/nZEDb#1576]
I downloaded the  nZEDb_x torrents linked to in the forum. I can import the bulk NZBs manually via cli (using nzb-import.php arg 1-n), but I do get "session" errors when I subsequently run try to my tmux session. Enabling "Import nzbs" via the web ui's "Tmux Settings Edit" page (my preferred method because of the automation) spawns the import nzb process (using import.php?) but asks for arguments - just as the manual import does. How do I pass arguments to a process running in a tmux frame? More specifically: how do I use threading with NZB imports?

**Comment by niel** [comment]
Have you correctly set the Import NZBs import path? That should be all you need to do to get it to work. However if the path is incorrect in some way, the Import NZB pane will not work correctly. That might manifest by complaining about missing parameters. It's a while since I've used it so don't recall exactly.

**Comment by DrakeJones** [comment]
You nailed it, niel. Problem solved. Thank you. I tried to use an invalid import path. I had the downloaded NZB folders on /mnt/hgfs/ on the host machine. Maybe it was a VM permissions issue, but whatever the case nZEDb didn't like it.
