### ISSUE TITLE
nzedb/utility/Utility.php variable $to not defined ?

### ISSUE THREAD

**Issue by Sweepr** [nZEDb/nZEDb#1596]
Using the contact form give's me a blank html page and php error_log show's:

PHP Fatal error:  Uncaught exception 'phpmailerException' with message 'Unable to send mail. Error: You must provide at least one recipient email address.' in /home/public_html/nZEDb/nzedb/utility/Utility.php:1113
Stack trace:
#0 /home/public_html/nZEDb/www/pages/contact-us.php(20): nzedb\utility\Utility::sendEmail('', 'Contact Form Su...', 'Values submitte...', 'contact@nzed...')
#1 /home/public_html/nZEDb/www/index.php(82): include('/home/...')
#2 {main}
  thrown in /home/public_html/nZEDb/nzedb/utility/Utility.php on line 1113

/nzedb/utility/Utility.php line 1103 show's

1103:  $mail->addAddress($to);

In settings.php on line 414:

define('PHPMAILER_REPLYTO', 'contact@nzedb.info');

 
Changed /nzedb/utility/Utility.php line 1103 into:

$mail->addAddress($replyTo);

And the contact form is send perfectly this time.
From and reply are both now "contact@nzedb.info"

Is this a bug or did i misconfigure something?

**Comment by kevinlekiller** [comment]
Looks more like this commit broke it, https://github.com/nZEDb/nZEDb/commit/c9e388243205b745cd5a1f70410abc987a0fee2b#diff-7ce4526946c2e4831a362f2de0e04142

$mailto and $email seem reversed.

**Comment by zetas** [comment]
That commit is fine. The reason I removed the From header is because headers are handled by phpmailer and should not be defined by the user. From the error posted it looks like theres some issue with this line: $mailto = $page->settings->getSetting('email');

If that database entry is blank, it will cause the error that you're having. The code doesn't handle an empty setting, but that's an existing issue before I implemented phpmailer. If we do indeed want to handle the empty db setting I can work up a PR to use the settings.php entry instead however using the PHPMAILER_REPLYTO as the fallback TO address is not really how it's supposed to work. I can hack in it but it would be better to just set the database entry or add an additional constant, something like PHPMAILER_EMAIL or something (even though this would be redundant and somewhat confusing to those that set the email in the site settings).

@Sweepr Please do me a favor and look in your "Site Settings -> Edit Site" section and see if this is empty: http://cl.ly/image/1i1D0x110c0L

**Comment by Sweepr** [comment]
@zetas 
Checked that setting and it was indeed empty, after setting the correct mail in there the form was sent out without issue.

Totally overlooked that in the settings, maybe good idea to move this out of site edit and into settings.php? where the rest of the Email optiomns are located?

**Comment by zetas** [comment]
Yea, there are a lot of weird settings like that. When i was doing the phpmailer integration I wasn't sure if they should go in settings.php or in the edit-site section. I opted for the file since they are settings that are presumably never changed and don't need to be maintained in the database. I'm all for moving the site email to the settings.php as well.

**Comment by Sweepr** [comment]
Thanks for clearing this up for me!

Closing this.
