### ISSUE TITLE
Parts Table Not Being Cleared

### ISSUE THREAD

**Issue by irishj** [nZEDb/nZEDb#1691]
Parts table not being cleared, keeps growing.  Tried reset_truncate.php, but grows again after that.

It was an issue recently and was fixed, but has started happening again.  On master branch ad8f6ed68

See this thread for details - http://forums.nzedb.com/index.php?topic=2023.0

**Comment by Bart39** [comment]
possibly related to https://github.com/nZEDb/nZEDb/commit/728716fce5ef13f40f39a549fe584177b9586aa3

release creation wasn't looping correctly - this will loop until all releases for a group are created

**Comment by irishj** [comment]
Updated to dev branch, reset_truncate and it's working again.  Thanks Bart39 !

**Comment by Bart39** [comment]
re-opened till it goes into master

**Comment by Bart39** [comment]
keep an eye on your C B P for the next couple of days and let me know how you get on

**Comment by Bart39** [comment]
merged to master

**Comment by tommytyker** [comment]
I was posting http://forums.nzedb.com/index.php?topic=2023.15 now I will post here.

Since I posted on the forum, my parts table grew to 18 million rows.. So I ran reset_truncate and started over. 2 weeks later, the table sat at 35 million rows.. I am having to run reset_truncate again. I am only indexing 11 groups...4 of them see very little activity. Let me know what I need to provide to help troubleshoot this
