### ISSUE TITLE
BUG: TMUX starting when it shouldn't

### ISSUE THREAD

**Issue by bobtongue** [nZEDb/nZEDb#1807]
I am on master. If I shutdown tmux from the tmux menu and then kill the session, when I restart tmux it starts automatically after the monitor refreshes regardless of whether the tmux switch in the tmux menu is on yes or no. It seems not to be looking for the running state on first blush. If I set TMUX to on and then back off, it will shut off fine and continue to pay attention to the switch until the session is killed. When started again it will display the same behavior. I m pretty sure this is new behavior since the last master update.

**Comment by DariusIII** [comment]
You see, when you start (or restart tmux, as you say) running state is set to yes, regardless of your setting in tmux part of admina area, because you, well, started tmux, right?
Btw, tmux has its own start/stop switches from cli, which "override" settings in admin area.

ie. php tmux-ui.php start will start thux session and set tmux to running state and php tmux-ui.php stop will stop tmux scripts and set tmux state to not running, but will not kill session, so if you issue start command again it will start from the point stop command was issued.

**Comment by bobtongue** [comment]
Is this a new design, because I don't remember it being like that before. Why would it follow that starting tmux means I want to start all of the scripts right away? After a pull I prefer to not start the scripts until the monitor has finished and I can see if things are running smooth. What is the point of having the tmux switch in the admin section if it doesn't work? Is it logical to have to turn tmux switch to on in the admin area and then shut it off to stop the scripts? NOt trying to be a smart ass here, just want to understand the logic.

**Comment by DariusIII** [comment]
If tmux is not killed, controls in admin area work. But if you kill the session and start again, everything is set to running.
