### ISSUE TITLE
TVRage shutdown. Replace it with tvmaze.com or thetvdb.com.

### ISSUE THREAD

**Issue by SchoolBusDriver** [nZEDb/nZEDb#1879]
TVRage website pulled the plug/shut down with a lot of their developers moving over to [tvmaze.com](http://www.tvmaze.com/).

We need to replace TVRage throughout nZEDb with either [tvmaze.com](http://www.tvmaze.com/) or[ thetvdb.com](http://thetvdb.com/).

**Comment by niel** [comment]
The admin of the site says he will be getting it back up ASAP. For the moment we will not be removing support. However we will be adding trakt and possibly other support as well.

**Comment by Fossil01** [comment]
TVMaze allows you to lookup stuff by using TVRage of TheTVDB ID's. They then redirect you to the correct show in their DB.

http://api.tvmaze.com/lookup/shows?tvrage=24493

If you already know a show's tvrage or thetvdb ID, you can use this endpoint to find this exact show on TVmaze. If the given ID can be matched, a HTTP 302 redirect to the show's URL will be returned. Otherwise, a HTTP 404 is sent.

**Comment by Bart39** [comment]
potential php wrapper - https://github.com/JPinkney/TVMaze-PHP-API-Wrapper

**Comment by ruhllatio** [comment]
I've got the Moinax TVDB API hooked into nzedb/libraries in my branch.  I can look at adding the others using the same methods.

**Comment by ruhllatio** [comment]
Done!
