### ISSUE TITLE
REQUEST: Run par2 file to rename release with par2 cmd?

### ISSUE THREAD

**Issue by Atmos01** [nZEDb/nZEDb#1926]
Hi,

Is it possible devs will create something to run the par2 files on releases so that the release is renamed?:

http://nzbindex.nl/release/127122303/2a75d3208126e49694c484c42ad6f430.vol00002-118-2a75d3208126e49694c484c42ad6f430.03.nzb

its 0day/mp3/flac

poster: http://nzbindex.nl/search/?sort=dateTime&poster=NoNo+%3Cbleeeeeeh%40blaaat.com%3E&max=25&more=1&p=0

**Comment by Wally73** [comment]
that already exists
https://github.com/nZEDb/nZEDb/blob/master/nzedb/config/settings.example.php#L142

**Comment by Atmos01** [comment]
It doesnt seem to work :D

**Comment by Bart39** [comment]
Yes it does...if they match against a pre title
"Rename releases using PAR2 files (if they match on PRE titles)"

**Comment by Wally73** [comment]
if a par2 file is also used to rename a file it will work too (at least it
should mostly ;) )

**Comment by Atmos01** [comment]
to bad its not working for mp3 and 0day in inner sactum :)

**Comment by Bart39** [comment]
its most likely due to inner-sanctum's pre feed dying so we have nothing to match the titles with

**Comment by ruhllatio** [comment]
I found why this isn't working.  Some change in the way an NZB file is parsed to determine whether or not a release has a PAR2 file.  Within the NZB, it is looking for filename.par2[" ].* blah blah blah.  When examing the NZBs however, they have filename.par2&quot (the html entity instead of the double quote symbol).  Long story short, It's fixed in dev-srr and will be merged once complete.  After making this change, even with really old releases I got plenty of PAR2 renames.
