### ISSUE TITLE
update_releases.php -> Call to undefined method finfo::close()

### ISSUE THREAD

**Issue by laurentverbruggen** [nZEDb/nZEDb#2001]
I'm trying to install nZEDb on my synology and everything seemed to work just fine until I executed update_releases.php and got the following PHP error:

`PHP Fatal error:  Call to undefined method finfo::close() in /volume1/web/nZEDb/nzedb/utility/Misc.php on line 474`

Executing update_binaries.php worked just fine. 
Do you guys have any idea what would be causing this error? 
If you need more information, please ask and I will provide.

**Comment by ruhllatio** [comment]
Did you get this resolved?  If not, looks like something's up with your extensions in PHP.  Curious, what version is your synology running?

**Comment by ruhllatio** [comment]
Okay, scratch that.  Looking in PHPStorm it's definitely giving me an error there because close doesn't exist in the class.  However, the correct set of builtin commands does exist that supports all of the options we're sending to the class.  So I don't quite understand the way we did it.  Testing my changes in Dev and will push if it looks good.

**Comment by laurentverbruggen** [comment]
Tested it with dev branch and it solved my issue. Thanks a lot!
