### ISSUE TITLE
Anidb Covers are not being Grabbed

### ISSUE THREAD

**Issue by OliverLeitner** [nZEDb/nZEDb#2077]
referring to:

https://github.com/nZEDb/nZEDb/issues/2072

screenshots and info included.

it might be some misconfiguration by me, but how do i do it correctly?

ps: if theres an option to reopen, please let me know, i didnt see it.

**Comment by OliverLeitner** [comment]
i think i found the problem.

anidb httpapi was in my case checking for an existing client AND a working client version.

register a client here (youll have to register and login on anidb as a user first):

http://anidb.net/perl-bin/animedb.pl?show=client

choose http api (default is udp), the name you choose here is what youll have to enter in nzedb admin panel.

as soon as youve registered your client, itll show you the client, on the right side of that entry, youll see "versions", click on it, set the version number to "2" (its currently hardcoded in nzedb/db/populate/AniDB.php to the number 2)

as soon as youre done with that, anime postprocessing will work just fine.

to the nzedb devs who are coding around with the postprocessing features, i think we'll need an extra field in "site-edit", right under the anidb "key". plus it might make it easier for the admins running this software to have the info with the "create a client first at anidb" somewhere near the "anidb api key" input field.

**Comment by b3rs3rk** [comment]
Please, stop.  The AniDB API client registration is for NEW client code.  Because you are using MY client code, you should be using MY client name and version number that I specify.  This is how they keep track of how many people are using a particular piece of code and who they need to talk to if something is wrong to make changes.  If your processing isn't working after entering 'nzedb' without the quotes into the AniDB API key field in Site Edit  and enabled Anime processing in Site Edit then you have a local problem.  No one else is reporting this issue and there have been 80k unique calls with my client today.  If you have a firewall, please make sure port 9001 is open outbound.

**Comment by b3rs3rk** [comment]
Forgot to add, you may need to run the pre-populate script in /cli/data if you don't have any anime_titles data populated in your database.  Without this, no AniDB calls will be made as they cannot be searched against without a known AniDB ID.

**Comment by OliverLeitner** [comment]
did the pre_population before i tried the url with your params, no firewall blocking, using your params gave me "wrong client data" from the anidb api, that is why i logged into my anidb account and checked what their wiki was saying about clientvers and client name in the first place. everything is fine and working for me now.
