### ISSUE TITLE
Missing file: app/libraries/autoload.php

### ISSUE THREAD

**Issue by qvistgaard** [nZEDb/nZEDb#2105]
### Expected behaviour

Installation page should be displayed
### Actual behaviour

Warning: require_once(app/libraries/autoload.php): failed to open stream: No such file or directory in /usr/local/www/nZEDb/autoloader.php on line 39

Fatal error: require_once(): Failed opening required 'app/libraries/autoload.php' (include_path='.:/usr/local/share/pear') in /usr/local/www/nZEDb/autoloader.php on line 39
### Steps to reproduce the behaviour

Follow install guide for freebsd/Freenas
File does not exists in git repo

**Comment by Wally73** [comment]
why do ppl don't read the changelog??? 
https://github.com/nZEDb/nZEDb/blob/dev/Changelog

**Comment by rcketscientist** [comment]
That's not a very helpful response especially considering as a new user I ran into the same problem and a new user isn't going to expect to need to peruse the changelog when there's such a seemingly complete setup guide.

You'll need to install composer.  
https://getcomposer.org/doc/00-intro.md#downloading-the-composer-executable
They recommend global, but since this was the only project I'm likely to need it on I simply downloaded the latest composer.phar to the nZEDb base directory.  Then call:
 `php composer.phar install`
if you do the global install i think you can simply:
`composer install`

It crashed on any memory_limit other than `-1` for me, but I'd run it first before changing that.

**Comment by rcketscientist** [comment]
do the global install, the new update system expects global.
