### ISSUE TITLE
Release not renamed, exact filename exists inside rar content. 

### ISSUE THREAD

**Issue by Sweepr** [nZEDb/nZEDb#2154]
I have in Other-misc releases that are obfuscated, if i view the release, the Rar content is showing me a file name with the correct name inside, but it is not being renamed accordingly?

I have tried php  fixReleaseNames.php with all options but no luck.

I have the option "Fix Release Names" set to yes in the tmux settings but still no luck.

http://forums.nzedb.com/index.php?topic=2241.0

**Comment by DariusIII** [comment]
That is because fixReleaseNames does not fix names in hashed categories.

**Comment by Sweepr** [comment]
Ok. Got that figures by now, what about Tmux?.. is it even possible?

**Comment by DariusIII** [comment]
Tmux uses same classes, so it cannot be different.

**Comment by Wally73** [comment]
https://github.com/nZEDb/nZEDb/blob/0.x/configuration/settings.example.php/settings.example.php#L146 in your renamed to settings.php set that to true 

and under Post Process Settings in nzedburl/site-edit.php turn on lookup par2

that might help (but from time to time releases slip thru

**Comment by Sweepr** [comment]
@Wally73 ok. Ill check that later today.

**Comment by Sweepr** [comment]
@Wally73 

Checked both settings and they are on..

**Comment by Wally73** [comment]
yeah ok as i mentioned sometimes they slip thru ( I notice that too from time to time )

**Comment by Bart39** [comment]
Some examples would be good

**Comment by Sweepr** [comment]
@Bart39 

For example this one: XAR160526MEMOWHYOAWTHKIWIPL

Group:  a.b.erotica.divx
Category:   Other > Misc

Rar Contains:  
Filename    Password    Size    Date
X-Art.16.05.26.Melissa.Moore.While.Youre.Away.The.Kitty.Will.Play.XXX.MP4-SDPORN.mp4    No  124.61 MB   May 27, 2016
xar160526memowhyoawthkiwipl.r00     No  14.31 MB    May 27, 2016
xar160526memowhyoawthkiwipl.r01     No  14.31 MB    May 27, 2016
xar160526memowhyoawthkiwipl.r02     No  14.31 MB    May 27, 2016
xar160526memowhyoawthkiwipl.r03     No  14.31 MB    May 27, 2016
xar160526memowhyoawthkiwipl.r04     No  14.31 MB    May 27, 2016
xar160526memowhyoawthkiwipl.r05     No  14.31 MB    May 27, 2016
xar160526memowhyoawthkiwipl.r06     No  14.31 MB    May 27, 2016
xar160526memowhyoawthkiwipl.r07     No  10.17 MB    May 27, 2016
xar160526memowhyoawthkiwipl.rar     No  14.31 MB    May 27, 2016

**Comment by Bart39** [comment]
The issue is that there is nothing to match those against, SDPORN is not a group that's pre'd (currently)
You know they are good release names by looking at them visually but we don't

**Comment by Sweepr** [comment]
Ah ok, so in short there's no way to rename the searchname based on the content found inside the rar.

**Comment by Bart39** [comment]
Not sure there's a consistent way to determine good from bad but will take a look

**Comment by ghost** [comment]
There is a proper filename in there. Can't we just use that for releases which cannot be renamed otherwise? Bigger chance the filename is correct than that the postname is correct IMHO.

**Comment by Sweepr** [comment]
@Fossil01 That's exactly the point of this issue. ;-)

**Comment by Bart39** [comment]
You know it's a good file name by looking at it.
But how do you prevent it from renaming to asdghjuygnj46784.mkv
E.g good from the bad

**Comment by ghost** [comment]
Well it's probably already gibberish so renaming it to the filename shouldn't matter then.

**Comment by DariusIII** [comment]
https://github.com/nZEDb/nZEDb/pull/2236

**Comment by CollinChaffin** [comment]
Hey @Wally73 , your link above for the answer, is dead.  Since it seemed to address the question, and I can't find a single doc that simply walks through that settings screen and just explains each config option, as one might expect - any chance you might re-post your answer file/screenshot, or anything actually showing what a "recommended" configuration might look like as of today in a given example configuration?

**Comment by CollinChaffin** [comment]
I just re-read every single posted guide doc, and not one even mentions going past the initial release download - which under no circumstances will EVER give an operator a fully populated indexer webpage.  There are (and have been) about 100 missing steps that it sure seems only the devs have the decoder ring to because I see posts of all the revs of fixReleasenames.php, yet you can literally grep it - these friggin scripts that MUST be run to get good results are NOT in any of the guides, let alone WTF we are supposed to do with them because running it 9 times with 9 different cmdlines with the 5 required args is certainly not what you devs have running by hand or even cron......so @Wally73  you seem to have the decoder ring......can you help the loley old user-base as to WTF all these php scripts are that apparently NEED to be run to get actual renamed files, but that are NOT being called automatically - namely starting with fixRelasenames.php that literally give THIS output:
````
bash-4.3# php fixReleaseNames.php
Error:
You must supply 4 arguments.
The 2nd argument, false, will display the results, but not change the name, type true to have the names changed.
The 3rd argument, other, will only do against other categories, to do against all categories use all, or preid to process all not matched to predb.
The 4th argument, yes, will set the release as checked, so the next time you run it will not be processed, to not set as checked type no.
The 5th argument (optional), show, will display the release changes or only show a counter.

php fixReleaseNames.php 1 false other no ...: Fix release names using the usenet subject in the past 3 hours with predb information.
php fixReleaseNames.php 2 false other no ...: Fix release names using the usenet subject with predb information.
php fixReleaseNames.php 3 false other no ...: Fix release names using NFO in the past 6 hours.
php fixReleaseNames.php 4 false other no ...: Fix release names using NFO.
php fixReleaseNames.php 5 false other no ...: Fix release names in misc categories using File Name in the past 6 hours.
php fixReleaseNames.php 6 false other no ...: Fix release names in misc categories using File Name.
php fixReleaseNames.php 7 false other no ...: Fix release names in misc categories using Par2 Files in the past 6 hours.
php fixReleaseNames.php 8 false other no ...: Fix release names in misc categories using Par2 Files.
php fixReleaseNames.php 9 false other no ...: Fix release names in misc categories using MediaInfo Unique_ID in the past 6 hours.
php fixReleaseNames.php 10 false other no ...: Fix release names in misc categories using MediaInfo Unique_ID.
````
Yet I KNOW for a FACT this needs to be run as it's finding the MAJORITY of my releases but obviously @Wally73 you're not sitting at home all day hitting up-arrow and looping these or cron jobbing them because it also appears in this blind BS trial and error testing I'm doing that I have to first reset the darn post processing to run the darn thing (that doesn't get run originally) to get any results....again.....lost....

I think it may even be your own gist or Stephen's that then had 3 other versions of the fixReleasenames.php that's regexing key posts by specific scene poster email addresses (for hashed files) which. despite me having qualified releases staring right back at me right now, again no way to know since no single doc anywhere actually even acknowledges that these scripts exist, are necessary, which one is used when, how to set them up, and when to use them...and some work and some don't when they should....and only you few DEVs have any idea and we are left in the dark.

I'm more than happy to add code and help test - but there has to be at least minimal documentation for key scripts/methods that are required to set up and make the app work, before the community can be much help in contributing.

**Comment by kaibosh** [comment]
Try github's search function to find the code wally was referring to.

Correct, that script is called more than 9 times with it's five arguments. See the simple-expanded.sh script for example usage.

There is no recommended configuration, everyone has different goals, hardware etc.

It's a pity the documentation did not meet your expectations. Any help would be appreciated.

**Comment by theblade954** [comment]
The page where @Wally73  was referring to https://github.com/nZEDb/nZEDb/blob/0.x/configuration/settings.example.php And then Line 145/146

But i am having the same troubles :-(  i have also adjusted that line... but still no fix?
Does someone hace a idea?

**Comment by theblade954** [comment]
@DariusIII  can you explain the idea of your link and how to use your fixes?
