### ISSUE TITLE
File Read Error (post process/additional NFO in tmux)

### ISSUE THREAD

**Issue by dilbaggins** [nZEDb/nZEDb#2255]
### Expected behaviour

No File Read Error 
### Actual behaviour

File Read error in the tmux pane when processing NFO causing releases to not be as frequent. i have not disabled the simple_yenc in the site settings as of yet.
### Steps to reproduce the behaviour

Version Details
Looking up Git tag version(s)
Hash: e3cbf2031e735ed656ed878a4359a0e8f4a0c3cb
XML version: v0.0.0-dev
Git version: v0.6.0.2
Looking up SQL patch version(s)
XML version: 448
 DB version: 448

**Comment by niel** [comment]
I would appreciate any more details you can provide. In particular what program is being accessed that causes this error.

**Comment by dilbaggins** [comment]
closed.  there was some files left in dir for some reason... removed and did a reset_truncate... alls well thanks @niel

**Comment by EDChurly** [comment]
I assume this is the E: File Read Error message in the post processing pane?

I believe this is caused by Mediainfo, which in the FAQ it mentioned it can happen if the file is not readable.

But I've noticed an increase of this since happening upgrading and not sure why... you said you removed some files left in a directory... which directory?

**Comment by dilbaggins** [comment]
@lulunzb there was some files in the /run/shm (TMPFS) i just removed manually vs rebooting.
