### ISSUE TITLE
fresh stable install errors on missing config.php

### ISSUE THREAD

**Issue by nrk666** [nZEDb/nZEDb#2291]
### Expected behaviour

Expected after installing via composer that http://<server>/install would start install process
### Actual behaviour

http://server/install -> HTTP ERROR 500

php_error.log in /var/www/nZEDb/www/install/ : 

`[15-Oct-2016 15:03:42 America/New_York] PHP Fatal error:  Uncaught RuntimeException: Unable to load configuration file '/var/www/nZEDb/nzedb/config/config.php'. Make sure it has been created and contains correct settings. in /var/www/nZEDb/nzedb/config/Configure.php:51
Stack trace:
#0 /var/www/nZEDb/nzedb/config/Configure.php(129): nzedb\config\Configure->loadSettings('config', true)
#1 /var/www/nZEDb/nzedb/config/Configure.php(42): nzedb\config\Configure->loadEnvironment('indexer')
#2 /var/www/nZEDb/nzedb/bootstrap.php(31): nzedb\config\Configure->__construct('indexer')
#3 /var/www/nZEDb/libraries/lithium/core/Libraries.php(325): require('/var/www/nZEDb/...')
#4 /var/www/nZEDb/libraries/lithium/core/Libraries.php(303): lithium\core\Libraries::_configure(Array)
#5 /var/www/nZEDb/app/config/bootstrap/libraries.php(135): lithium\core\Libraries::add('nzedb', Array)
#6 /var/www/nZEDb/app/config/bootstrap.php(34): require('/var/www/nZEDb/...')
#7 /var/www/nZEDb/www/smarty.php(22): require_once('/var/www/nZEDb/...')
#8 /var/www/nZEDb/www/install/index.php(3): require_once in /var/www/nZEDb/nzedb/config/Configure.php on line 51`
### Steps to reproduce the behaviour

composer create-project --no-dev --keep-vcs --prefer-source nzedb/nzedb nZEDb

browser to : http://server/install   -> HTTP ERROR 500

OS: ubuntu 16.04 / php7 / MariaDB 10 

Version : 
git branch -v
- (HEAD detached at v0.6.5.2) 3febee8 Update version xml
  0.x  59ac112 Update versions file.

Note: this system was working with an older version of nZEDb, Nginx/MariaDB/PHP setup was not modified except to drop the nzedb database (to start over) and to remove /var/www/nZEDb (to start over). DB user access perms and php modifications were not changed. Nginx config was not changed. 

config.php doesn't exist in a fresh install, I'd imagine that is what the install process is designed to build.

**Comment by niel** [comment]
Can you be more specific on the older version that did work. It may help to narrow down when the problem was introduced, as I'm currently unable to reproduce this by your steps. However, our test-install script does complain about the install being locked. So there's obviously something weird going on.

**Comment by MikeOsborn** [comment]
I ran into the same issue using the latest source code.  The config.php file is not created on a clean install and the installation pages expect a database with the settings table to exist before they function correctly.

In order to get things sort of working, I copied the nZEDb/www/install/config.php.tpl to nZEDb/nzedb/config/config.php and filled out the parameters by hand.  I then created the database and the settings table by hand.  Once that was done I was able to work through the installation web pages.  Step6 appears to be failing to load the settings correctly.  Once finished with the installation pages, my admin account appears to get logged in but is denied access to the admin pages.

**Comment by niel** [comment]
@MikeOsborn You're mostly correct, the installation process is supposed to ignore the requirement for the config to exist. For some reason it is not currently.
I am soooooo tempted to remove the web install completely, but that might be an overreaction ;-)

**Comment by niel** [comment]
And that last message gave me an idea. I now know where it is happening, but haven't a clue why ;-)
I'll keep at it though.

**Comment by niel** [comment]
OK, I think I have this nailed in dev branch. I'll create a new release for stable branch tomorrow.

**Comment by nrk666** [comment]
niel: I'm not sure of the exact "old" release, but it has been a couple months since I did a new install.  I wasn't installing over top though, I "rm -rf" /var/www/nZEDb and did a DROP on the nzedb database before I tried installing from scratch. The only reason I mentioned it working on that box before was to illustrate that I didn't think it was an external software issue like php or some other missing component.

**Comment by nrk666** [comment]
Sounds like you may have figured it out anyway, look forward to the new release to try again. Thanks for looking into it.

**Comment by ralphte** [comment]
For people that hit this error and just need to use the installer change this line is the file /var/www/nZEDb/nzedb/config/Configure.php

FROM

'indexer' => [
                        'config'        => true,
                        'settings'      => false
TO

'indexer' => [
                        'config'        => false,
                        'settings'      => false

Then change it back after you have gone though the install. This is a quick fix till this is fixed updstream
