### ISSUE TITLE
Ahem - Adult Releases not renamed ?

### ISSUE THREAD

**Issue by PsychoSid** [nZEDb/nZEDb#2472]
###Expected behaviour
Adult releases not being renamed correctly ?

###Actual behaviour
Should be renamed

###Steps to reproduce the behaviour
Run updates etc

Not that I am especially bothered (honest !) but just running through things on the site since the update and noticed that at of all things the Adult stuff seems not to be named/renamed correctly all others seem fine:-
$ ./zed version all
Looking up Git tag version(s)
Hash: 84a81108a9112f0b018215e6696f02bf88f09e3c
XML version: 0.7.3.1
Git version: 0.7.3.1
Looking up SQL patch version(s)
XML version: 482
 DB version: 482

< wckdpctrs my brthrs grlfrnd fllhd >-[01/97] - "wckdpctrs my brthrs grlfrnd fllhd par2"  for example.

**Comment by Bart39** [comment]
That's not going to match anything, not a scene release or even anything to work out quality etc

**Comment by PsychoSid** [comment]
Yeah - dunno to be fair. Just know I got a lot of human readable releases prior to the latest update.

Thanks

**Comment by sspilleman** [comment]
Not related to (the last version of) nzedb I guess. Looks like its a new thing to post stuff in that manner.... See:

https://www.nzbindex.nl/search/?q=wckdpctrs&age=&max=25&minage=&sort=agedesc&minsize=&maxsize=&dq=&poster=&hidespam=0&hidespam=1&more=0

**Comment by sspilleman** [comment]
Please ignore my previous comment. Although its true, a lot of names are mangled... In this it *should* have renamed it... Its in PreDB.

**Comment by bgidi** [comment]
It's because the posters at a.b.e now use a new format.

It's no longer:

    [278997]-[FULL]-[#a.b.erotica]-[ chi-the.walking.dead.xxx ]-[06/51] - "chi-the.walking.dead.xxx-s.mp4" yEnc

It's now: 

    < wckdpctrs.my.brthrs.grlfrnd.hd >-[01/47] - "wckdpctrs.my.brthrs.grlfrnd.hd.par2" yEnc

or

    [ ntgrl.17.06.14.y.4k ]-[01/94] - "ntgrl.17.06.14.y.4k-Sample.mp4" yEnc 

The ID are now missing from the subject but filenames have corresponding entries in the PreDB.

I think the collection regex should be something like:

    \[(?P<match0>.+?)\][- ]\[\d+\/\d+\] - ".+?" yEnc$

and

    \<(?P<match0>.+?)\>[- ]\[\d+\/\d+\] - ".+?" yEnc$

However, I haven't tested yet.


I saw a new format for packs too:

    [ 544891 ]-[01/12] - "18_1983.v.l.grnd.scs.1.par2" yEnc

The ID is still there for those, so I guess they can be matched with PreDB.

**Comment by bgidi** [comment]
I did a bit of testing and **new** posts are correctly renamed with these _regex_ when the filenames match a _PreDB_ entry.
I set the ordinals in the 20s because 85, 90 etc didn't seem to work (maybe a conflict with other regex).
They aren't perfect but it's better than nothing. Just a slightly modified version of the existing ones.

---

Subject :

    foo.17.06.10.bar-[66/73] - "foo.17.06.10.bar.vol000+01.par2" yEnc

Collections Regex

    /(?P<match0>.+?)[- ]\[\d+\/\d+\] - ".+?" yEnc$/

Release Naming Regex

    /(?P<match0>.+?)[- ]\[\d+\/\d+\] - "([\w\säöüÄÖÜß+¤?¶!.,&_\()\[\]\'\`{}#-]{8,}?\b.?)([-_](proof|sample|thumbs?))*(\.part\d*(\.rar)?|\.rar|\.7z)?(\d{1,3}\.rev"|\.vol.+?"|\.[A-Za-z0-9]{2,4}"|")[-_\s]{0,3}yEnc$/


---

Subjects :

    [foo.17.06.14.bar.4k]-[01/94] - "foo.17.06.14.bar.4k-Sample.mp4" yEnc
    <foo.17.06.14.bar.4k>-[01/94] - "foo.17.06.14.bar.4k-Sample.mp4" yEnc
    [ foo.17.06.14.bar.4k ]-[01/94] - "foo.17.06.14.bar.4k-Sample.mp4" yEnc
    < foo.17.06.14.bar.4k >-[01/94] - "foo.17.06.14.bar.4k-Sample.mp4" yEnc


Collections Regex

    /[\[,\<](?P<match0>.+?)[\],\>][- ]\[\d+\/\d+\] - ".+?" yEnc$/

Release Naming Regex

    /[\[,\<]\s*(?P<match0>.+?)\s*[\],\>][- ]\[\d+\/\d+\] - "([\w\säöüÄÖÜß+¤?¶!.,&_\()\[\]\'\`{}#-]{8,}?\b.?)([-_](proof|sample|thumbs?))*(\.part\d*(\.rar)?|\.rar|\.7z)?(\d{1,3}\.rev"|\.vol.+?"|\.[A-Za-z0-9]{2,4}"|")[-_\s]{0,3}yEnc$/

---

**Comment by Bart39** [comment]
i'll add these in - good spot

**Comment by sspilleman** [comment]
Appreciate the good analysis and work! tx

**Comment by bgidi** [comment]
The problem with my regex is they may be too vague and may catch too many "subjects". But you get the idea.
