### ISSUE TITLE
Whilst updating tables, a sort order is needed

### ISSUE THREAD

**Issue by devmem** [nZEDb/nZEDb#2482]
For some reason, my release_naming_regexes were out of id order. When updating to 0.7.3.2, the following patch was attempted to be applied:

UPDATE release_naming_regexes SET id = id - 3 WHERE id BETWEEN 752 AND 1159;

Because my table is not stored in incrementing id's, this failed as it attempted to renumber id 1033 to 1030 before it had renumbered id 1030. This failed with the error message:

Error: UPDATE release_naming_regexes SET id = id - 3 WHERE id BETWEEN 752 AND 1159; Failed \{1062}
   Duplicate entry '1030' for key 'PRIMARY'

It appears another user has exactly the same issue as me as shown here: http://forums.nzedb.com/index.php?topic=2419.msg13348#msg13348

To fix the issue, the line was replaced by 

UPDATE release_naming_regexes SET id = id - 3 WHERE id BETWEEN 752 AND 1159 ORDER BY id ASC;

This returns the dataset in a format suitable for processing.

**Comment by niel** [comment]
This is fixed in dev. I'll prepare a new stable release later.

**Comment by niel** [comment]
Fixed in dev.

**Comment by hansenhans** [comment]
Is this fix already in stable? I'm asking because I had the same problem, but with different ids.

I solved it by commenting out the line which caused the problem in the patch and running

`for i in {752..1159}; do mysql -u nzedb -ppassword -e "UPDATE release_naming_regexes SET id = id - 3 WHERE id = $i ORDER BY 'id' ASC;" nzedb; done`

from the command line. Will there be a problem with my workaround in the future?

**Comment by niel** [comment]
@hansenhans It is in stable now.

If you had already have run the old patch, it is too late for the fix. You'll have to reload the tables.
