### ISSUE TITLE
zed's dead

### ISSUE THREAD

**Issue by OliverLeitner** [nZEDb/nZEDb#2530]
Expected: ./zed update all to work

What happens:

./zed update all
sh: 1: Syntax error: "(" unexpected

**Comment by lawsontyler** [comment]
This happens because it tries to find your git branch, but you've checked out a tag.

If you checked out a tag, (e.g. `git checkout v0.8.3.0`) nzedb sees the current branch as "(HEAD detached at v0.8.3.0)"

It then goes on and tries to use the branch in commands, so things like `git pull origin (HEAD detached at v0.8.3.0)` fail because /bin/sh recognizes brackets as something special.

The short-term fix is to use a real branch like dev.  The long-term fix is going to be somewhere in `app/libraries/nzedb/Git.php/*` so that it doesn't try to execute dumb things or `app/extensions/util/Git.php` so that it's smart enough to not send dumb things to its libraries inputs.  Or both.

**Comment by niel** [comment]
@lawsontyler could you back up that statement with some info on how this is failing, please. 
There is a test in the code that is supposed to prevent this kind of thing https://github.com/nZEDb/nZEDb/blob/0.x/app/extensions/command/Update.php#L109 if you can tell me how this is failing, I'll happily fix it.

**Comment by lawsontyler** [comment]
`./zed update all` calls the `nzedb` method.  That method was unsafely assuming it could run `$this->git->pull()`, which looks up the current branch, which is `(HEAD detached at v0.8.3.0)`, and injects that into the git command.

Sorry, my comment stemmed from my fuzzy memory of the last time I tracked it down.  I finally put some time into it again and found the issue, which is fixed by the PR.

**Comment by niel** [comment]
Pushed to dev branch
