### ISSUE TITLE
Releases spanning multiple groups

### ISSUE THREAD

**Issue by hondnl** [nZEDb/nZEDb#2538]
A lot of releases are now spanning multiple groups.

For each rar file they dump it into a different group.  The current indexer is not picking up on that.

For example :
```

  <file poster="Bob &lt;bob@homef.me&gt;" date="1509354887" subject="[ Wisdom.Of.The.Crowd.S01E05.1080p.AMZN.WEB-DL.DD5.1.H.264-NTb ] - &#34;Wisdom.of.the.Crowd.S01E05.Clear.History.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part64.rar&#34; yEnc (01/66)">
    <groups>
      <group>alt.binaries.misc</group>
    </groups>
```
```
<file poster="Bob &lt;bob@homef.me&gt;" date="1509354917" subject="[ Wisdom.Of.The.Crowd.S01E05.1080p.AMZN.WEB-DL.DD5.1.H.264-NTb ] - &#34;Wisdom.of.the.Crowd.S01E05.Clear.History.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.part36.rar&#34; yEnc (01/66)">
    <groups>
      <group>alt.binaries.x</group>
    </groups>
    <segments>
```

etc...

**Comment by blimeybloke** [comment]
I was going to ask the exact question.  I noticed this too.  Another example due to yours having a TV title:

`
<file poster="-3VxjJEIgMd@vuOKp.a76" date="1509333756" subject="d6169f56ffc94b2780eac27d1ddce0e0 &quot;d6169f56ffc94b2780eac27d1ddce0e0.par2&quot; yEnc (1/1)">
    <groups>
      <group>alt.binaries.xylo</group>
    </groups>`
` <file poster="hf1ywNGI9ZtuG1WDAUPJo@jI2f6lBzoK.b5H" date="1509333756" subject="d6169f56ffc94b2780eac27d1ddce0e0 &quot;d6169f56ffc94b2780eac27d1ddce0e0.part01.rar&quot; yEnc (1/102)">
    <groups>
      <group>alt.binaries.goonies</group>
    </groups>`
`  <file poster="WbRKJPPpOqoV5A-R8Tkow@s5w1FZvfw2.SI_" date="1509333759" subject="d6169f56ffc94b2780eac27d1ddce0e0 &quot;d6169f56ffc94b2780eac27d1ddce0e0.part02.rar&quot; yEnc (1/102)">
    <groups>
      <group>alt.binaries.goat</group>
    </groups>`

**Comment by niel** [comment]
This has been happening for a while where the titles are hashed and only the poster's name is the same. We have code that covers that, but nothing for this latest version where it is done plain text.
Writing new code to handle this will take some time, as it appears this move is designed to deliberately screw with us, as our tables only store one group, making it hard to impossible to do the comparing.

**Comment by blimeybloke** [comment]
oh, but if you import the nzb, it will save it.  I tried that to see if it would cause mass chaos but it didn't.

Dumb question, could you store the group_id as an array to support the multi group posts?  Sorry if its dumb, I am no where near a level to assist but like HR on the Flash, I am all about ideas.

**Comment by niel** [comment]
We're investigating alternatives now. We already have group-names/ids as a separate table, so an "array" as you mention is possible. Unfortunately we used to store all articles in a single table, it rapidly got too large to handle, which is why we use separate tables now and find ourselves in this situation.

**Comment by blimeybloke** [comment]
Whats comical is that the uploaders are trying to stop us, but the pay indexing sites are making money off their uploads.  Its sort of backwards.  I do it so I do not have to pay for an indexing site and host it on a home box that used to be my old desktop. I allow exactly 3 mates access and no one else.  I think I may have been bought a lager once for running it.

**Comment by jangrewe** [comment]
@blimeybloke i'd like to entertain the thought that some sites are giving some uploaders a cut of their profits, if the uploaders adhere to an uploading schema for which the sites have the logic to put everything back together. there's no benefit in it for the uploader if he'd do it deliberately just for himself, because if he's able to stop "us", there are probably no regular users that can make any sense of it.

**Comment by blimeybloke** [comment]
@jangrewe You are probably right.  Would be pointless to upload and have no one know what it is.  I still think they are making it easier to shut down.  If you funnel everything instead of how it was wide open, it puts a pretty easy mark on the indexing sites.
