### ISSUE TITLE
Base table or view not found

### ISSUE THREAD

**Issue by jangrewe** [nZEDb/nZEDb#2556]
###Expected behaviour
Processing doesn't show any errors.

###Actual behaviour
Processing does show errors.
The groups in the screenshot below are not, and never were, activated.
![error](https://i.snag.gy/Rx5Fge.jpg)

###Steps to reproduce the behaviour
I have no idea... ;-)

**Comment by niel** [comment]
You'll have to create the missing table.

**Comment by jangrewe** [comment]
Hehe, yes, that would be a solution. I guess i wrote this in a hurry, which is why it's a bit short...
I was thinking that maybe the scripts should check if the tables they're about to query do actually exist?
I haven't looked at the particular query, but why would it check those tables if the groups were never active, and how does it come up with them anyways? ;-)

**Comment by niel** [comment]
There are times when it checks and other times it assumes the table exists, the same way it 'assumes' the table is valid and not corrupt.
The number on the end of the table name comes from the group's id. So it is assumes that collections_14 exists, because you were fetching headers for group 14. If for some reason that table didn't get created, or became corrupt, or the file system lost it, you end up with the error you are experiencing.
We'll be changing the code in this area in the next few months. In the mean time, you need to create the table manually.

**Comment by cronexiler** [comment]
This happens to me when I activate a new group from admin site while tmux is doing binaries/backfill prior to running releases script.
I just ignore it and it creates the tables on the next binaries loop.

**Comment by blimeybloke** [comment]
I have about 30 tables that are spitting the same error.  Is there an easy way to recreate these?  Or am I stuck doing this all manually?  Hopefully there is a script in /dev or something :)

**Comment by niel** [comment]
No script currently. I'll look into creating one this weekend.

**Comment by blimeybloke** [comment]
@niel thanks, I think it will be a great way to fix this easily for when things fall out of sync.

**Comment by Rawh** [comment]
Getting the same error for three tables with a different number at the end. Any luck with the script @niel  or should I just copy the setup/layout from a different id/number and use that within sql?

**Comment by niel** [comment]
I had to refactor the Verify console command in order to allow for adding this, and that took longer than expected.
I recently updated our code review app (Scrutinizer) to use the new analysis engine and that has revealed hundreds of potential problems. I'm working through them as a priority. Once that is complete 
I will get back to this.

**Comment by niel** [comment]
@Rawh For now you can use SQL. The statement should look something like this:
CREATE TABLE IF NOT EXISTS \<tablePrefix>_\<groupID> LIKE \<tablePrefix>
Replace \<tablePrefix> with the table type (binaries, collections, missing_parts, or parts) and \<groupID> with the ID number of the group as reported in the error.

**Comment by JReming85** [comment]
Always happens to me when adding new groups as active/backfill too quickly.

Im going to play around with it, but I think it might see active + backfill and think that since its active the table has already been made.

I'll keep you posted

Yup, atleast in my case that was the issue.

Was clicking backfill beforeit had a chance to create the table.

Try clicking "Activate" waiting for it to do a scrape pass and then click "Backfill"
