### ISSUE TITLE
': bool' in Misc.php and Model.php creates errors which stops nginx

### ISSUE THREAD

**Issue by MrHappy** [nZEDb/nZEDb#2580]
###Expected behaviour
let nginx start as it should

###Actual behaviour
nginx doesn't start
and generates:
2018/05/08 21:55:12 [error] 9636#9636: *1 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /var/www/nZEDb/app/extensions/data/Model.php on line 43" while reading response header from upstream, client: <localip>, server: <fqdn>, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "<fqdn>"

###Steps to reproduce the behaviour
install php7.0 and try to start nginx.
removing all ': bool' from the lines in nzedb/utility/Misc.php & app/extensions/data/Model.php resolves the issue for me..

**Comment by DariusIII** [comment]
Can you install PHP7.1? 

That should fix your issue.

**Comment by niel** [comment]
Your description is not correct. I have PHP 7.0 and nginx and do NOT get the problem.

The problem is that you previously have had PHP 5.6 installed and it has not properly been removed. The ": bool" lines you are removing are syntax introduced with PHP 7.0 and so will work with a correctly installed and working PHP 7.0

**Comment by MrHappy** [comment]
@niel thanks... Thought I had removed it all, but apparently I didn't...
Took some tinkering on my end, but now everything is working great (again).
Thanks!
