### ISSUE TITLE
Browsegroups shows incorrect information (no active groups)

### ISSUE THREAD

**Issue by Rawh** [nZEDb/nZEDb#2592]
###Expected behaviour
Browse groups on website shows the groups and time since last update (+ release amount)

###Actual behaviour
Browse groups shows groups I haven't added to my site. It has no information worth seeing but for some reason it shows groups that aren't active.

###Steps to reproduce the behaviour
No clue :(

My admin site & active groups:
[Admin site](https://user-images.githubusercontent.com/10486655/43065616-a85521d8-8e62-11e8-983f-2787fc6b5b36.png)

My Browsegroups page:
[Browsegroup](https://user-images.githubusercontent.com/10486655/43065632-b754d3d6-8e62-11e8-9ec4-a6ea9e71ea05.png)

I'm running release v0.8.8.1 with db verrsion 484. I have theme Alpha selected as default. Switching to Charisma has the same issue.

**Comment by niel** [comment]
Which theme?

**Comment by Rawh** [comment]
I noticed Alpha and Gamma both have it.

**Comment by niel** [comment]
This isn't a bug, although there are some minor improvements to /browsegroups for the next release.
The release count was removed, as it has terrible performance on the database, and clicking the group name will take you to a list of those releases (and then you'll see how slow that lookup is.).

We're considering adding a filter for the groups shown to allow user choice of enabled/disabled/all (defaulting to enabled). However this is a low priority compared to other work, because it would involve changing all of the themes and development of the Smarty themes is halted.
