### ISSUE TITLE
Initial Header Pull of new group is not respecting age setting.

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2605]
###Expected behaviour
Initial pull of new group setting of 1 day or 1000000 headers will pull 1 days worth or 1000000 headers

###Actual behaviour
Initial pull downloads ALL headers all the way back to oldest.

###Steps to reproduce the behaviour
add new group, pull headers

**Comment by Benouch** [comment]
Hi there,
I concur.
After adding a new group and running update_binaries Local newest is set to 0 + Max headers iteration.
Where it should be set to 1 day or 1000000 depending on the config.
The only way to fix it is to edit the group manually and add the server newest into Last Record ID - the number of articles one wants. It's quite cumbersome when there are many groups.
Because of this backfill doesn't work either.

**Comment by Benouch** [comment]
Hello again,
I not sure it's the right place to post this but I'm doing it anyway.
The issue comes from this line (421) in nZEDb/Binaries.php
if ($groupMySQL['last_record'] === 0) {...}
This checks if we are running update binaries for the first time.
=== checks for equal values but also for equal types.
$groupMySQL['last_record'] is a string but 0 is an int. So the condition is always false regardless if we are running the update binaries for the first time.
I don't really know what the coding policies are but we can do the following:
Either this:
if ($groupMySQL['last_record'] == 0) {...}
Or that:
if ($groupMySQL['last_record'] === "0") {...}
Or make sure $groupMySQL['last_record'] is of type int.

**Comment by DariusIII** [comment]
Actually it should be:
Either 
`if ((int) $groupMySQL['last_record'] === 0) {}`
Or
`if ($groupMySQL['last_record'] === '0') {}`

But i prefer the first one.

**Comment by Benouch** [comment]
Thanks for explanation.
There's a similar issue with nZEDb/Backfill.php line 224.

**Comment by niel** [comment]
@Benouch I'm looking into this now (have been for a couple days, but your first post gave me a new clue to follow).
Although those lines look bad, I'm thinking it might actually be the $this->_newGroupMessagesToScan / $this->_newGroupDaysToScan not being set correctly in the constructor.
I'm trying to test it.

**Comment by Benouch** [comment]
Hi @niel ,
I'm glad I could help.

**Comment by niel** [comment]
@Benouch Can you explain what you mean about Backfill line 224. The situation there is the opposite so in what way is it similar?

**Comment by Benouch** [comment]
Hello @niel ,
You're right there's nothing wrong in Backfill.php line 224.
I got ahead of myself...

**Comment by niel** [comment]
@Benouch good. In that case I think we can call this done.
Fix is in dev branch and will get merged into stable branch next Monday.

**Comment by Benouch** [comment]
Hi @niel ,
Thank you.
